name: Deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test
    # if: ${{ startsWith(github.event.release.tag_name, 'test/') }}
    steps:
      - uses: actions/checkout@v3
      - run: bash .github/scripts/deploy.sh
        env:
          GITHUB_REPOSITORY_PASSED_BY_VAR: ${{ github.repository }}
